version: '3'

tasks:
  install:
    desc: Install frontend dependencies
    cmds:
      - npm ci

  dev:
    desc: Start the Vite dev server
    cmds:
      - npm run dev

  build:
    desc: Build the frontend
    cmds:
      - npm run build

  lint:
    desc: Lint the frontend
    cmds:
      - npm run lint

  test:
    desc: Run frontend tests
    cmds:
      - npm test

  generate:
    desc: Generate API client from OpenAPI
    cmds:
      - npm run generate
