openapi: 3.0.3
info:
  title: Codex Demo API
  version: 1.0.0
  description: A minimal OpenAPI definition used to generate server and client code.
servers:
  - url: http://localhost:8080
paths:
  /api/hello:
    get:
      tags:
        - hello
      summary: Say hello
      operationId: getHello
      responses:
        '200':
          description: A hello message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
        default:
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    HelloResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: Hello from Spring Boot
    ErrorResponse:
      type: object
      required:
        - code
        - message
        - traceId
        - timestamp
        - path
      properties:
        code:
          type: string
          example: INTERNAL_ERROR
        message:
          type: string
          example: Unexpected error
        traceId:
          type: string
          example: 2b6b8b22-9b31-4c96-8a22-f6a2d2e4c1c4
        details:
          $ref: '#/components/schemas/ErrorDetails'
        timestamp:
          type: string
          format: date-time
          example: 2026-02-01T12:34:56Z
        path:
          type: string
          example: /api/hello
    ErrorDetails:
      type: object
      additionalProperties: true
      properties:
        fieldErrors:
          type: array
          items:
            $ref: '#/components/schemas/FieldError'
    FieldError:
      type: object
      required:
        - field
        - message
      properties:
        field:
          type: string
          example: name
        message:
          type: string
          example: must not be blank
        rejectedValue:
          type: string
          nullable: true
          example: ""
