/* eslint-disable */
// This file is generated by openapi-typescript from openapi/api.yml.
export interface HelloResponse {
  message: string;
}

export interface paths {
  '/api/hello': {
    get: {
      responses: {
        200: {
          content: {
            'application/json': HelloResponse;
          };
        };
      };
    };
  };
}
